@extends('layouts.app')
@section('title','Laporan Periode')
@section('content')
<div class="page-header"><div><p class="muted">{{ $report->name }}</p><h1>Laporan Periode</h1></div></div>
<form class="card inline-form no-print" method="get">
  <div class="field"><label for="from">Tanggal awal</label><input class="input" id="from" name="from" type="date" value="{{ $from }}" required></div>
  <div class="field"><label for="to">Tanggal akhir</label><input class="input" id="to" name="to" type="date" value="{{ $to }}" required></div>
  <div class="field"><label for="type">Arus transaksi</label><select class="input" id="type" name="type"><option value="">Pemasukan dan Pengeluaran</option><option value="IN" @selected(($data['type']??'')==='IN')>Pemasukan</option><option value="OUT" @selected(($data['type']??'')==='OUT')>Pengeluaran</option></select></div>
  <div class="field"><label for="category">Kategori</label><select class="input" id="category" name="category"><option value="">Semua</option>@foreach($categories as $cat)<option value="{{ $cat->id }}" @selected(($data['category']??'')==$cat->id)>{{ $cat->name }}</option>@endforeach</select></div>
  <button class="btn btn-secondary">Tampilkan</button>
</form>
<div class="grid metrics" style="margin:1rem 0"><div class="card"><div class="metric-label">Saldo sebelum periode</div><div class="metric-value">Rp {{ number_format($summary['before'],0,',','.') }}</div></div><div class="card"><div class="metric-label">Pemasukan periode</div><div class="metric-value">Rp {{ number_format($summary['incoming'],0,',','.') }}</div></div><div class="card"><div class="metric-label">Pengeluaran periode</div><div class="metric-value">Rp {{ number_format($summary['outgoing'],0,',','.') }}</div></div><div class="card"><div class="metric-label">Saldo akhir</div><div class="metric-value {{ $summary['ending']<0?'negative':'' }}">Rp {{ number_format($summary['ending'],0,',','.') }}</div></div></div>
<div class="actions no-print" style="margin-bottom:1rem"><form method="post" action="{{ route('period.export',$report) }}">@csrf<input type="hidden" name="from" value="{{ $from }}"><input type="hidden" name="to" value="{{ $to }}"><input type="hidden" name="type" value="{{ $data['type']??'' }}"><input type="hidden" name="category" value="{{ $data['category']??'' }}"><button class="btn btn-primary">Buat PDF</button></form></div>
<section class="card"><h2 class="section-title">Transaksi {{ \Carbon\Carbon::parse($from)->format('d/m/Y') }}–{{ \Carbon\Carbon::parse($to)->format('d/m/Y') }}</h2>@if($transactions->isEmpty())<div class="empty">Tidak ada transaksi pada periode ini.</div>@else<div class="table-wrap"><table><thead><tr><th>No</th><th>Tanggal</th><th>Keterangan</th><th class="number">Pengeluaran</th><th class="number">Pemasukan</th><th>Kategori</th></tr></thead><tbody>@foreach($transactions as $tx)<tr><td>{{ $transactions->firstItem()+$loop->index }}</td><td>{{ $tx->transaction_date->format('d/m/Y') }}</td><td>{{ $tx->description ?: 'Tanpa keterangan' }}</td><td class="number">{{ $tx->type==='OUT'?'Rp '.number_format($tx->amount,0,',','.'):'—' }}</td><td class="number">{{ $tx->type==='IN'?'Rp '.number_format($tx->amount,0,',','.'):'—' }}</td><td>{{ $tx->category?->name??'—' }}</td></tr>@endforeach</tbody></table></div>{{ $transactions->links() }}@endif</section>
<section class="card no-print" style="margin-top:1rem"><h2 class="section-title">Status PDF</h2>@forelse($exports as $export)<div style="display:flex;justify-content:space-between;padding:.6rem 0;border-bottom:1px solid #e1e5e2"><span>{{ $export->starts_on->format('d/m/Y') }}–{{ $export->ends_on->format('d/m/Y') }} · <strong>{{ $export->status }}</strong></span>@if($export->status==='READY')<a href="{{ route('pdf.download',$export) }}">Unduh PDF</a>@endif</div>@empty<p class="muted">Belum ada PDF.</p>@endforelse</section>
@endsection
